services:
  db_postgres:
    container_name: db_postgres_SortCheck
    image: postgres:15.2-alpine
    ports:
      - "6748:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345